import 'package:flutter/material.dart';
import 'package:flutter/src/foundation/key.dart';
import 'package:flutter/src/widgets/framework.dart';

class busi extends StatelessWidget {
  const busi({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
        child: SafeArea(
          child: Padding(
            padding: const EdgeInsets.only(left: 5),
            child: Column(
              children: [
                SizedBox(
                  height: 15,
                ),
                Image.asset('assets/b1.jpg'),
                Container(
                  height: 250,
                  child: ListView(
                    scrollDirection: Axis.horizontal,
                    shrinkWrap: true,
                    children: [
                      Image.asset('assets/b2.jpg'),
                      Image.asset('assets/b3.jpg'),
                      Image.asset('assets/b4.jpg')
                    ],
                  ),
                ),
                Image.asset('assets/x1.jpg'),
                Container(
                  height: 250,
                  child: ListView(
                    shrinkWrap: true,
                    scrollDirection: Axis.horizontal,
                    children: [
                      Image.asset('assets/x2.jpg'),
                      Image.asset('assets/x3.jpg'),
                      Image.asset('assets/x4.jpg'),
                    ],
                  ),
                ),
                Image.asset('assets/t1.jpg'),
                Container(
                  height: 270,
                  child: ListView(
                    shrinkWrap: true,
                    scrollDirection: Axis.horizontal,
                    children: [
                      Image.asset('assets/t2.jpg'),
                      Image.asset('assets/t3.jpg')
                    ],
                  ),
                ),
                Image.asset('assets/al1.jpg'),
                Image.asset('assets/al2.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al1.jpg'),
                Image.asset('assets/al2.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al1.jpg'),
                Image.asset('assets/al2.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al1.jpg'),
                Image.asset('assets/al2.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al1.jpg'),
                Image.asset('assets/al2.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al1.jpg'),
                Image.asset('assets/al2.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al1.jpg'),
                Image.asset('assets/al2.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al1.jpg'),
                Image.asset('assets/al2.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al1.jpg'),
                Image.asset('assets/al2.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al1.jpg'),
                Image.asset('assets/al2.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al1.jpg'),
                Image.asset('assets/al2.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
