import 'package:flutter/material.dart';

class fin extends StatelessWidget {
  const fin({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: SingleChildScrollView(
          child: Padding(
            padding: const EdgeInsets.only(left: 10),
            child: Column(
              children: [
                Padding(
                  padding: const EdgeInsets.only(top: 30, left: 5),
                  child: Text(
                    'Finance  & Accounting',
                    style: TextStyle(fontSize: 30, fontWeight: FontWeight.bold),
                  ),
                ),
                // ignore: prefer_const_constructors
                Padding(
                  padding: const EdgeInsets.only(top: 35, left: 5),
                  child: Text(
                    'Courses to get you started',
                    style: TextStyle(fontSize: 25, fontWeight: FontWeight.bold),
                  ),
                ),
                Image.asset('assets/x1.jpg'),
                Container(
                  height: 250,
                  child: ListView(
                    shrinkWrap: true,
                    scrollDirection: Axis.horizontal,
                    children: [
                      Image.asset('assets/x2.jpg'),
                      Image.asset('assets/x3.jpg'),
                      Image.asset('assets/x4.jpg'),
                    ],
                  ),
                ),
                Image.asset('assets/t1.jpg'),
                Container(
                  height: 270,
                  child: ListView(
                    shrinkWrap: true,
                    scrollDirection: Axis.horizontal,
                    children: [
                      Image.asset('assets/t2.jpg'),
                      Image.asset('assets/t3.jpg')
                    ],
                  ),
                ),
                Image.asset('assets/al1.jpg'),
                Image.asset('assets/al2.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al1.jpg'),
                Image.asset('assets/al2.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al1.jpg'),
                Image.asset('assets/al2.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al1.jpg'),
                Image.asset('assets/al2.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al1.jpg'),
                Image.asset('assets/al2.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al1.jpg'),
                Image.asset('assets/al2.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al1.jpg'),
                Image.asset('assets/al2.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al1.jpg'),
                Image.asset('assets/al2.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al1.jpg'),
                Image.asset('assets/al2.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al1.jpg'),
                Image.asset('assets/al2.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
                Image.asset('assets/al8.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al1.jpg'),
                Image.asset('assets/al2.jpg'),
                Image.asset('assets/al3.jpg'),
                Image.asset('assets/al4.jpg'),
                Image.asset('assets/al5.jpg'),
                Image.asset('assets/al6.jpg'),
                Image.asset('assets/al7.jpg'),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
