import 'package:flutter/material.dart';
import 'package:flutter/src/foundation/key.dart';
import 'package:flutter/src/widgets/framework.dart';

class tab1 extends StatelessWidget {
  const tab1({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: SingleChildScrollView(
        child: SafeArea(
          child: Column(
            children: [
              Image.asset('assets/111.jpg'),
              Container(
                height: 250,
                child: ListView(
                  shrinkWrap: true,
                  scrollDirection: Axis.horizontal,
                  children: [
                    Image.asset(
                      'assets/112.jpg',
                      scale: 4,
                    ),
                    Image.asset(
                      'assets/113.jpg',
                      scale: 4,
                    ),
                    Image.asset(
                      'assets/114.jpg',
                      scale: 4,
                    ),
                  ],
                ),
              ),
              Padding(
                padding: const EdgeInsets.only(right: 65),
                child: Image.asset(
                  'assets/z1.jpg',
                  scale: 2,
                ),
              ),
              SizedBox(
                width: 25,
              ),
              Padding(
                padding: const EdgeInsets.only(left: 10),
                child: Container(
                  height: 250,
                  child: ListView(
                    shrinkWrap: true,
                    scrollDirection: Axis.horizontal,
                    children: [
                      Image.asset('assets/z2.jpg'),
                      SizedBox(
                        width: 15,
                      ),
                      Image.asset('assets/z3.jpg'),
                      SizedBox(
                        width: 15,
                      ),
                      Image.asset('assets/z4.jpg'),
                      SizedBox(
                        width: 15,
                      ),
                    ],
                  ),
                ),
              ),
              Image.asset('assets/t1.jpg'),
              Container(
                height: 270,
                child: ListView(
                  shrinkWrap: true,
                  scrollDirection: Axis.horizontal,
                  children: [
                    Image.asset('assets/t2.jpg'),
                    Image.asset('assets/t3.jpg')
                  ],
                ),
              ),
              Image.asset('assets/al1.jpg'),
              Image.asset('assets/al2.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al1.jpg'),
              Image.asset('assets/al2.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al1.jpg'),
              Image.asset('assets/al2.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al1.jpg'),
              Image.asset('assets/al2.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al1.jpg'),
              Image.asset('assets/al2.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al1.jpg'),
              Image.asset('assets/al2.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al1.jpg'),
              Image.asset('assets/al2.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al1.jpg'),
              Image.asset('assets/al2.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al1.jpg'),
              Image.asset('assets/al2.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al1.jpg'),
              Image.asset('assets/al2.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al1.jpg'),
              Image.asset('assets/al2.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
            ],
          ),
        ),
      ),
    );
  }
}
