import 'package:flutter/material.dart';
import 'package:flutter/src/foundation/key.dart';
import 'package:flutter/src/widgets/framework.dart';

class tab2 extends StatelessWidget {
  const tab2({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
        child: SafeArea(
          child: Column(
            children: [
              Image.asset('assets/ee.jpg'),
              Container(
                height: 250,
                child: ListView(
                  shrinkWrap: true,
                  scrollDirection: Axis.horizontal,
                  children: [
                    Image.asset('assets/tt1.jpg'),
                    Image.asset('assets/tt2.jpg'),
                    Image.asset('assets/tt3.jpg'),
                    Image.asset('assets/tt4.jpg'),
                    Image.asset('assets/tt5.jpg'),
                  ],
                ),
              ),
              Image.asset('assets/x1.jpg'),
              Container(
                height: 250,
                child: ListView(
                  shrinkWrap: true,
                  scrollDirection: Axis.horizontal,
                  children: [
                    Image.asset('assets/x2.jpg'),
                    Image.asset('assets/x3.jpg'),
                    Image.asset('assets/x4.jpg'),
                  ],
                ),
              ),
              Image.asset('assets/t1.jpg'),
              Container(
                height: 270,
                child: ListView(
                  shrinkWrap: true,
                  scrollDirection: Axis.horizontal,
                  children: [
                    Image.asset('assets/t2.jpg'),
                    Image.asset('assets/t3.jpg')
                  ],
                ),
              ),
              Image.asset('assets/al1.jpg'),
              Image.asset('assets/al2.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al1.jpg'),
              Image.asset('assets/al2.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al1.jpg'),
              Image.asset('assets/al2.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al1.jpg'),
              Image.asset('assets/al2.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al1.jpg'),
              Image.asset('assets/al2.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al1.jpg'),
              Image.asset('assets/al2.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al1.jpg'),
              Image.asset('assets/al2.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al1.jpg'),
              Image.asset('assets/al2.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al1.jpg'),
              Image.asset('assets/al2.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al1.jpg'),
              Image.asset('assets/al2.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
              Image.asset('assets/al8.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al1.jpg'),
              Image.asset('assets/al2.jpg'),
              Image.asset('assets/al3.jpg'),
              Image.asset('assets/al4.jpg'),
              Image.asset('assets/al5.jpg'),
              Image.asset('assets/al6.jpg'),
              Image.asset('assets/al7.jpg'),
            ],
          ),
        ),
      ),
    );
  }
}
